### ISSUE TITLE
[Feature] Display Skeleton Frame Before All Post Information is Rendered on Screen

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#325]
Currently, the skeleton is displayed for 1 second. However, we need to improve this functionality so that the skeleton appears while fetching all the necessary data. The skeleton should disappear only after all the content has successfully loaded. The current issue is that, after 1 second, some content still hasn’t rendered properly.

**Comment by 1chooo** [comment]
@mu-irfan Apologies, but after our discussion yesterday, I still believe it might be worth spending some time researching the skeleton effect. I’ve assigned this issue to you as well, but it’s not mandatory. If you'd like to discuss it further, feel free to reach out. Thank you again for your contribution!

related: #315

**Comment by irfen-mi** [comment]
@1chooo Alright, will try to do it today.

**Comment by 1chooo** [comment]
https://codeinmyday.com/blog/how-to-use-skeleton-loading-in-nextjs

**Comment by 1chooo** [comment]
@mu-irfan We have conducted research on how to achieve our goal for this issue. Thank you again for your amazing work! Please visit https://1chooo.com/post to review the effect!

**Comment by irfen-mi** [comment]
@1chooo Alright cool, you're welcome.
