### ISSUE TITLE
[Enhancement] Add Skeleton Screen Effect while Loading Blog

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#75]
The current effect of loading blog may let user confuse what will load, we can add the skeleton screen effect to improve the user experience 

### Current Screenshots
| | |
|-|-|
| ![image](https://github.com/user-attachments/assets/ec291b5c-5996-4874-b5d7-c7471fdc601f) | ![image](https://github.com/user-attachments/assets/4e056df1-8313-4174-aedd-2f3e2d802966) |

### Reference 

- https://mui.com/material-ui/react-skeleton/
- https://www.npmjs.com/package/react-loading-skeletons
- https://www.smashingmagazine.com/2020/04/skeleton-screens-react/
- https://blog.logrocket.com/build-skeleton-screen-css/

**Comment by 1chooo** [comment]
Follow this tutorial: https://www.youtube.com/watch?v=g74Q0wRc6BQ, Maybe we have to refactor the blog post at first.

**Comment by 1chooo** [comment]
https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

**Comment by irfen-mi** [comment]
hey @1chooo 
i can add skeleton loader or screen for your site, so whenever data is loading we can display the skeleton.

**Comment by 1chooo** [comment]
> hey @1chooo i can add skeleton loader or screen for your site, so whenever data is loading we can display the skeleton.

@mu-irfan really appreciate!! I’ll attach the details later.
